services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:4.0-management"
    env_file: .env
    ports:
      - ${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    networks:
      - tpp-network
    volumes:
      - /etc/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

networks:
  tpp-network:
    external: true
